include ../../make/make.inc

BASEDIR			= ../..
BUILDDIR		=	.
BUILD_FLAGS		+= -Wno-deprecated-declarations
LIBPATHS		+= 
LIBS        	+= -ldl -lstrategy
INCLUDEPATHS 	+= -I$(BASEDIR)/strategy -I$(BASEDIR)/io -I$(BASEDIR)/md -I$(BASEDIR)/td -I$(BASEDIR)/account -I$(BASEDIR)/risk -I$(BASEDIR)/ThirdParty/CTP -I$(BASEDIR)/logger -I$(BASEDIR)/bar
VPATH 			+= $(BASEDIR)/strategy


build			= demo_stg single_demo


build: ${build}

demo_stg: CDemoStrategy.o CEncodeConv.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o ${RELEASE}/$@

single_demo: CDemo.o CEncodeConv.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o ${RELEASE}/$@

# must put at the end
include ../../make/tail.inc

