include ../make/make.inc

#CC		=	
#LD     =	

BUILDDIR		=	.
BUILD_FLAGS		+= -DFAST_LOGGER_ -Wno-deprecated-declarations
LIBPATHS		+= -L$(BASEDIR)/ThirdParty/CTP
LIBS        	:= -lpthread -lstdc++ -ldl -lthostmduserapi -lthosttraderapi -lboost_python -lpython2.7
INCLUDEPATHS 	+= -I$(BASEDIR)/io -I$(BASEDIR)/md -I$(BASEDIR)/td -I$(BASEDIR)/account -I$(BASEDIR)/risk -I$(BASEDIR)/ThirdParty/CTP \
                   -I$(BASEDIR)/logger -I/usr/include/python2.7 -I$(BASEDIR)/pyext -I$(BASEDIR)/bar
VPATH 			+= $(BASEDIR)/io $(BASEDIR)/account $(BASEDIR)/risk $(BASEDIR)/md $(BASEDIR)/td $(BASEDIR)/logger $(BASEDIR)/pyext \
					$(BASEDIR)/bar


build			= libstrategy.so


build: ${build}

libstrategy.so: CStrategyProcess.o CStrategy.o CMDHelperFactory.o CTDHelperFactory.o CLogPool.o CFastLog.o FastLogger.o \
 IMDHelper.o ITDHelper.o CMDHelperComm.o CTDHelperComm.o CSystemIO.o CMDHelperReplayIO.o CTDHelperFake.o CIOBase.o utils.o \
 CTimer.o CRawIOReader.o CRawIOWriter.o CSignal.o MurmurHash2.o CGlobalLock.o CGlobalSafeRawIOWriter.o StrategyShared.o CTradeBaseInfo.o \
 ATSysUtils.o PyExtension.o PyUtils.o PyWrapper.o BarMaker.o Bar2.o BarHelper.o \
 UnitVol.o UnitAmt.o UnitPx.o UnitPnl.o ModInstr.o ModPrd.o ModAcc.o AccBase.o\
 ConfUtil.o RiskInstr.o RiskInstrStg.o RiskInstrTop.o RiskPrd.o RiskAcc.o RiskStg.o RiskTop.o\
 CWareHouseReader.o CMDHelperReplayCtpDump.o CMDHelperPipe.o CTDHelperPipe.o CPipExecutor.o\
 CTDHelperPython.o CMDHelperPython.o PyExtExch.o
	${CC} ${BUILD_FLAGS} -shared $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o ${RELEASE}/$@
	cp ${RELEASE}/$@ $(BASEDIR)/lib


# must put at the end
include ../make/tail.inc

 
