* Getting the source
  The third party libraries (such as, EES, CTP ...) are integrated into the source base
  as git submodule.

  The command to clone the whole source base including ThirdParty libraries is:
  ~git clone --recurse-submodules -b <branch_name> <repo_address>~
  
* Build and install
** Prerequisite
*** /python2.7/
    #+begin_src shell
    sudo apt install python2-dev
    #+end_src
*** /boost 1.72.00/ 
    1. checkout version 1.72.0 in the git repo:
      #+BEGIN_SRC bash
        git checkout -f -b boost-1.72.0 boost-1.72.0
        git submodule update --init
        rm -rf .git/modules/disjoint_sets
      #+END_SRC 
    2. build and install boost (/boost_python/ should be built against /python2.7/)
       #+BEGIN_SRC bash
         ./bootstrap --prefix=/home/yong/boost/1.72.0 --with-python=python2
         ./b2 install
       #+END_SRC
*** /CMake/ latest (>=3.15)
    #+begin_src shell
    sudo apt install cmake cmake-curses-gui
    #+end_src
*** /autotools/ is needed to build libev
    #+begin_src shell
    sudo apt install automake autoconf m4 libtool
    #+end_src
*** /openssl/
    #+begin_src shell
    sudo apt install openssl
    #+end_src
*** /cvs/
    This is needed to fetch *libev* source code from CVS server.
    #+begin_src shell
    sudo apt intall cvs
    #+end_src
    
** Dependencies
*** External (i.e. source available)
**** *log4cplus*
     Used in *logger* package, which is a common package used by almost all other packages.
**** *libev*
     
     Used in the package *tunnel_agent* and *signal_agent*.
*** ThirdParty (i.e. only binary library available)
    Different trading libraries (API) are integrated:
**** CTP
     Current, version v6.3.19 is used.
     But the code base use v6.3.8 (see *UnitedMarketDataType* defined in [[file:src/include/Constant.h][the common header]] and [[file:src/dump/Structure.h][the dump package header]] )
**** EES
**** Xt     
     
** Configure & Build
  The build system is *CMake* by:
  #+begin_src shell
  cd $git_repo$ & mkdir build & cd build
  cmake -DCMAKE_INSTALL_PPREFIX=<XXX> -DBoost_ROOT=<XXX> -denable_libev_build=on ../src
  make -j8
  make install
  #+end_src
  
*** CMAKE_INSTALL_PREFIX
    The default installation prefix is */home/jarvis* if user does not pass in customized /CMAKE_INSTALL_RPEFXI/.

*** ENABLE_LIBEV_BUILD
    This option controls whether building library /libev/ in the cmake configuration stage.
    The default value is *ON*.
    /libev/ should at least be built once.
    Normally, in the first time of cmake configuration, the option should be *ON* so that /libev/ is built.
    In the following times, the option can be set to *OFF* to save time of configuration.
    
*** Boost_ROOT
    The directory points to the installation direcotry of /boost/ library.
    
*** PYTHON2_ROOT_DIR
    The directory of python2 installation. This option normally can be ignored.
    /CMake/ could find the correct python2 by itself if there is only one version of python2 installed.
    If several versions of /python2/ installed, this option should point to the one which is used to complie /boost/ library.
    
* Caveants
    
* Running the servers
** /TDEngine/ and /MDEngine/
   The most essential servers are the /MDEngine/ for the market quotes and /TDEngine/ for the trade transactions.

   Cautions:
   - running the servers need root privilege
   - /TDEngine/ needs to be invoked first and run successfully (for the base information), then /MDEngine/ could be invoked
   - Both engines are run as daemon by default
   - The configuration file used can be found in these scripts

*** Method1
   Each server is an independent process, which has its own directory under the installation direcotry.
   An script (under $CMAKE_INSTALL_PREFIX$/MDEngine/scripts/md_svr.sh and $CMAKE_INSTALL_PREFIX$/TDEngine/scripts/td_svr.sh)
   is provided to facilitate the setup of the running environment of each server.
#+begin_src bash
  # TDEngine
  cd $CMAKE_INSTALL_PREFIX$/TDEngine/scripts # or MDEngine direcotry
  sudo ./td_svr.sh start/stop
#+end_src

*** Method2
   An overall script (under $CMAKE_INSTALL_PREFIX$/scripts/engine_svr.sh) exist to correctly load the /TDEngine/ and /MDEngine/ together.
   #+begin_src shell
     cd CMAKE_INSTALL_PREFIX/MDEngine/scripts
     sudo ./engine_svr.sh start/stop
   #+end_src
