include ../make/make.inc

#CC		=	
#LD     =	

BUILDDIR		=	.
BUILD_FLAGS		+= -Wno-deprecated-declarations
LIBPATHS		+= -L$(BASEDIR)/ThirdParty/CTP -L$(BASEDIR)/ThirdParty/Xt
LIBS        	+= -ldl
INCLUDEPATHS 	+= -I$(BASEDIR)/io -I$(BASEDIR)/account -I$(BASEDIR)/risk -I$(BASEDIR)/ThirdParty/CTP -I$(BASEDIR)/ThirdParty/Xt
VPATH 			+= $(BASEDIR)/io $(BASEDIR)/account $(BASEDIR)/risk
RELEASE         := ../../release/TDEngine/bin

build			= ${RELEASE}/TDEngine ${RELEASE}/TDEngineEESV2 ${RELEASE}/TDEngineXt ${RELEASE}/TDEngineEESV31347

build: ${build}

${RELEASE}/TDEngine: INCLUDEPATHS += -I$(BASEDIR)/ThirdParty/EES
${RELEASE}/TDEngine: LIBS += -L$(BASEDIR)/ThirdParty/EES
${RELEASE}/TDEngine: TDEngine.o ITDEngine.o CSystemIO.o CEncodeConv.o CTradeBaseInfo.o COrderTrackMmap.o \
 UnitVol.o UnitAmt.o UnitPx.o UnitPnl.o ModInstr.o ModPrd.o ModAcc.o AccBase.o\
 ConfUtil.o RiskInstr.o RiskInstrStg.o RiskInstrTop.o RiskPrd.o RiskAcc.o RiskStg.o RiskTop.o\
 CTDEngineCtp.o CTDEngineEES.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} $(BASEDIR)/io/libio.a ${INCLUDEPATHS} -o $@ -lthostmduserapi -lthosttraderapi -lEESTraderApi

${RELEASE}/TDEngineEESV2: INCLUDEPATHS += -I$(BASEDIR)/ThirdParty/EESV2
${RELEASE}/TDEngineEESV2: LIBS += -L$(BASEDIR)/ThirdParty/EESV2
${RELEASE}/TDEngineEESV2: TDEngineEESV2.o ITDEngine.o CSystemIO.o CEncodeConv.o CTradeBaseInfo.o COrderTrackMmap.o \
 UnitVol.o UnitAmt.o UnitPx.o UnitPnl.o ModInstr.o ModPrd.o ModAcc.o AccBase.o\
 ConfUtil.o RiskInstr.o RiskInstrStg.o RiskInstrTop.o RiskPrd.o RiskAcc.o RiskStg.o RiskTop.o\
 CTDEngineCtp.o CTDEngineEESV2.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} $(BASEDIR)/io/libio.a ${INCLUDEPATHS} -o $@ -lthostmduserapi -lthosttraderapi -lEESTraderApi
	
${RELEASE}/TDEngineXt: TDEngineXt.o ITDEngine.o CSystemIO.o CEncodeConv.o CTradeBaseInfo.o COrderTrackMmap.o \
 UnitVol.o UnitAmt.o UnitPx.o UnitPnl.o ModInstr.o ModPrd.o ModAcc.o AccBase.o\
 ConfUtil.o RiskInstr.o RiskInstrStg.o RiskInstrTop.o RiskPrd.o RiskAcc.o RiskStg.o RiskTop.o\
 CTDEngineXt.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} $(BASEDIR)/io/libio.a ${INCLUDEPATHS} -o $@ -lXtTraderApi
	
${RELEASE}/TDEngineEESV31347: INCLUDEPATHS += -I$(BASEDIR)/ThirdParty/EES3_1_3_47
${RELEASE}/TDEngineEESV31347: LIBS += -L$(BASEDIR)/ThirdParty/EES3_1_3_47
${RELEASE}/TDEngineEESV31347: TDEngine.o ITDEngine.o CSystemIO.o CEncodeConv.o CTradeBaseInfo.o COrderTrackMmap.o \
 UnitVol.o UnitAmt.o UnitPx.o UnitPnl.o ModInstr.o ModPrd.o ModAcc.o AccBase.o\
 ConfUtil.o RiskInstr.o RiskInstrStg.o RiskInstrTop.o RiskPrd.o RiskAcc.o RiskStg.o RiskTop.o\
 CTDEngineCtp.o CTDEngineEES.o
	${CC} ${BUILD_FLAGS} -c ${INCLUDEPATHS} -o CTDEngineEES.o CTDEngineEES.cpp
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} $(BASEDIR)/io/libio.a ${INCLUDEPATHS} -o $@ -lthostmduserapi -lthosttraderapi -lEESTraderApi

# must put at the end
include ../make/tail.inc

