include ../make/make.inc

#CC		=	
#LD     =	

BUILDDIR		=	.
BUILD_FLAGS		+= -Wno-deprecated-declarations
LIBPATHS		+= -L$(BASEDIR)/ThirdParty/CTP
LIBS        	+= -lthostmduserapi -lthosttraderapi
INCLUDEPATHS 	+= -I$(BASEDIR)/ThirdParty/CTP 
VPATH 			+= 
RELEASE			:= ../../release/dump/bin


build			:= ${RELEASE}/CTPDumper


build: ${build}

${RELEASE}/CTPDumper: CTPDumper.o CCTPTD.o CCTPMD.o FileMgr.o DailyInfoMgr.o utils.o CEncodeConv.o CTimer.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o $@

# must put at the end
include ../make/tail.inc

