include ../make/make.inc

#CC		=	
#LD     =	

BUILDDIR		=	.
BUILD_FLAGS		+= -Wno-deprecated-declarations
LIBPATHS		+= -L$(BASEDIR)/ThirdParty/CTP -L$(BASEDIR)/ThirdParty/EES
LIBS        	+= -lthosttraderapi -lthostmduserapi -lEESQuoteApi -lEESTraderApi -ldl
INCLUDEPATHS 	+= -I$(BASEDIR)/config -I$(BASEDIR)/ThirdParty/CTP -I$(BASEDIR)/ThirdParty/EES
VPATH 			+=
RELEASE			:= ../../release/TradeTool

build := ${RELEASE}/TradeTool

${RELEASE}/TradeTool: TradeTool.o CTraderFactory.o CTraderBase.o CGlobalParameter.o CCtpTrader.o CCtpMiniTrader.o CRisk.o CEncodeConv.o CEESTrader.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o $@


# must put at the end
include ../make/tail.inc

