
* 常见问题
  
** CTP API调用init后为啥没有任何反应？
   1）先检查网络链路是否畅通，可以telnet一下行情前置地址，是否通畅。

   2）再检查API版本是否正确，连生产或者simnow现必须是6.3.15版本api，版本不正确将没有回调。

   提醒：simnow正常地址是交易时间使用，7*24小时地址是非交易时段可以使用。

** 怎么知道有哪些合约正在交易（有行情）？
   NGES行情API里面很坑的一点是没有查询合约的功能。虽然二代行情里面加了ReqQryMulticastInstrument接口，但也仅是查询组播合约，需要咨询期货公司是否连接到相关交易所组播行情。所以有三种做法获取合约号：

   1）通过交易CTP API登录调用函数ReqQryInstrument查询；

   2）爬交易所网站获得可交易合约；
   
   3）交易所可交易合约有规则，例如上期白银为当前月开始的下个月的连续12个合约，当前为8月，那即是从ag1909到ag2008，找出这些规则生成合约编码即可

** 为什么登陆上了订阅显示成功但没有行情？
   首先确保是否订阅成功。CTP坑的是无论你订阅什么合约id，都会返回你"CTP:No Error"，但只有你填对了合约编码才有相应行情。所以：

   1）检查编码是否正确。这里坑的是各交易所对命名格式并不统一，命名规则如下：
   期货合约如下：前面字母代表品种名，后面数字代表合约到期日。
   上期/能源所：小写+4个数字（rb1909代表rb品种，19年9月份到期）
   中金所：大写+4个数字
   郑商所：大写+3个数字(TA001代表TA品种，20年01月份到期)
   大商所：小写+4个数字
   
   期权合约如下：标的期货合约+看涨/看跌+行权价
   上期所：小写+四个数字+C（或者P）+行权价，如cu1912C43000
   大商所：小写+四个数字+ -C-（或者-P-）+ 行权价，如c2001-C-1800
   郑商所：大写+三个数字+C（或者P）+行权价，如CF001C11200
   中金所：大写+四个数字+ -C-（或者-P-）+ 行权价，如IO1908-C-2100

   2）检查你订阅的行情是否过期。如果现在是19年8月份，那你订阅的是rb1905这种5月份到期的合约那肯定是没有行情的。

   3）检查是否订阅的合约是冷门合约，冷门合约行情跳动比较少。可以打开相应客户端看下，找主力合约订阅。

** CTP提供的是实时tick数据吗？
   CTP提供的是实时tick数据，但不是真正的tick数据。tick数据一般是指市场上的逐笔数据，例如一笔委托会产生一笔行情，一笔成交也会产生一笔行情。目前国内期货交易所还不支持推送这种逐笔的数据，只推送切片（快照）数据。切片数据是指将一定时间内的逐笔数据统一成一个快照发出，一般是1秒2笔。但郑商所有点特殊，可能是1s多笔，就不展开来讲了。 

** TradingDay和ActionDay有什么区别？
   在CTP的设计里，TradingDay用来表示交易日，ActionDay表示当前实际日期。期货交易分为日夜盘，这两个日期在日盘的时候是一致的，但在夜盘就有了区别，是因为当天夜盘是属于第二天这个交易日。例如20190830（周五）晚上21点开始交易，交易日TradingDay是20190902（周一），但实际日期ActionDay是20190830。

   这是设计的初衷，但事实上夜盘各交易所这两个日期很混乱。我们以20190830晚上夜盘交易举例：
   tradingday actionday
   上期/能源 20190902 20190830
   大商所 20190902 20190902
   郑商所 20190830 20190830

   总结就是，大商所夜盘两个日期都是tradingday，郑商所日夜盘都是当天日期。

** 非交易时段收到行情是怎么回事？
   日盘盘前可能会收到行情，是因为CTP日盘起动时会重演夜盘的流水，所以有可能会将夜盘的行情再推送一遍。日盘结束后也会收到行情，这是交易所结算完成发出的行情，这里面的结算价字段是当日结算价，一般推送时间在3点~3点半。建议按照交易时间过滤掉这些非盘中行情，以免影响交易逻辑。

** 可以通过CTP API获得历史行情吗？
   不可以，CTP只提供实时行情。获取历史行情，目前免费的可以从天勤获取，仅提供所有期货合约。收费的可以从上海闪策信息科技获取，提供国内股票，期货及美国股票及期货相关所有历史数据。

** CTP提供level2行情吗？
   level2行情是指深度行情，不同于level1只有1档，level2有多档。但除上期和能源外，一般交易所多档行情是收费行情，所以深度行情需要咨询相应期货公司。具体哪些交易所提供哪些行情，收费情况，会单独放一章出来讲。

   目前上期和能源的level2行情对期货公司是免费的，但各个期货公司用哪家系统转发，要不要收费就要看他们自己了。所以最好去咨询期货公司，可以多咨询几家。至于在有些客户端上为啥能看到五档行情，因为那些客户端是接了自己公司的行情服务器，不一定是连CTP收的

**  如何获取当前切片内的成交量？
   Volume字段是累计成交量，这里是指这个交易日内的累计成交量。如需要这个切片内的成交量，需要用这个切片的该字段值，减去上个切片相应值，差额即是这个切片内成交量。
   
**  为什么有的字段值特别大？
   行情中常看到有数值是1.7976931348623157e+308，这是double类型的上限值，在CTP内部是表示无效的。例如盘中的时候，本次结算价字段SettlementPrice即为无效值。

**  行情均价AveragePrice字段有什么坑？
   AveragePrice这个字段除郑商所可以直接拿过来用之外，其它四大交易所要除以合约乘数，才是真正的均价。至于合约乘数是什么百度吧，可以通过用交易API查询合约获得，或者去交易所网站上查询获得。
   
** 行情里面的Exchange ID字段为空？
   是的，发过来就是空值，需要自己维护，可以从交易接口查询合约ReqQryInstrument得到。

** 请问投资者结算结果确认是什么意思?有什么用?
   投资者在登录后首先需要确认自己的结算单(即账单)，结算单确认后才可以进行 交易操作。终端可以使用 ReqSettlementInfoConfirm 请求确认结算单，请求时只需要填 写经纪公司代码和投资者代码。查询结算单使用 ReqQrySettlementInfo，不填日期，表 示取上一交易日结算单。使用 ReqQrySettlementInfoConfirm 可以查询当天客户结算单确 认情况，无记录返回表示当天未确认结算单，为避免客户当天多次登陆多次重复确认结 算单，建议在确认前先查询当天是否已经确认，如果客户已经确认过则不需要再次重复 确认。

** 程序使用TradeApi和MdApi，并且把这2个dll放在同一个目录下。程序再次启动后， 如果某个 api 采用 Resume 模式订阅公有流/私有流，就会去参考相关的本地流文件。可 能会导致数据异常?
   相同目录下的 2 个 dll 会把数据写入相同本地流文件，导致 2 个 dll 不断的覆盖对方 写下的流文件。程序再次启动时，TradeApi 可能去参考 MdApi 写下的流文件，所以导致 数据流不连续。解决方法:如果一定要把 2 个 dll 放在相同的目录下，可以在创建 api 时指定流文件的路径。使得不同的 dll 写入不同流文件。

** 查询流量限制
   CTP API交易接口中的查询操作的限制为:
   1) 每秒钟最多只能进行一次查询操作。 
   2) 在途的查询操作最多只能有一个。 在途:查询操作从发送请求，到接收到响应为一个完整的过程。如果请求已经发送，但是未收到响应，则称 该查询操作在途。
    
   上述限制只针对交易接口中的数据查询操作(ReqQryXXX)，对报单，撤单，报价，询价等操作没有影响。

** 报单流量限制
   报单流量限制是由期货公司通过在系统中配置相关参数实现限制的。 不进行配置的情况下，默认流量限制为:
   1) 在一个连接会话(Session)中，每个客户端每秒钟最多只能发送6笔交易相关的指令(报单，撤单等)。 
   2) 同一个账户同时最多只能建立6个会话(Session)。
      
   注意:报单操作超过限制时，不会有错误返回，只是报单会处于排队状态，等待处理。该限制包含包括报单， 撤单，查询等所有请求操作。

** 断线重连
   客户端与服务端断开连接时，函数 OnFrontDisconnected 被调用，其中的参数nReason描述了断线的原因。
