* SimNow (上期所期货模拟仿真系统）
  
** [[http://www.simnow.com.cn/product.action][Platform environment]]
   
   统一BrokerID : 9999
                      
***  标准CTP:
    
   | Group (组） | Trade Front (交易前置) | Market Front (行情前置) | 网络供应商 |
   |           1 |  180.168.146.187:10100 |   180.168.146.187:10110 | 电信       |
   |           2 |  180.168.146.187:10101 |   180.168.146.187:10111 | 电信       |
   |           3 |  218.202.237.33 :10102 |   218.202.237.33 :10112 | 移动       |
   
   用户注册后，默认的APPID为simnow_client_test，认证码为0000000000000000（16个0），默认不开终端认证，程序化用户可以选择不开终端认证接入。

   交易阶段(服务时间)：与实际生产环境保持一致。

   CTP FIX 网关（看穿式）：
        第一组：Trade Front: 180.168.146.187:10104，Market Front：180.168.146.187:10114；【电信】
        CTP FIX网关相关资料请到常用下载->综合交易平台api下载页面查看。
        交易阶段(服务时间)：与实际生产环境保持一致。
        
***   7*24小时环境:
    
   | Group (组） | Trade Front (交易前置) | Market Front (行情前置) | 网络供应商 |
   |           1 |  180.168.146.187:10130 |   180.168.146.187:10131 | 电信       |

   第二套环境仅服务于CTP API开发爱好者，仅为用户提供CTP API测试需求，不提供结算等其它服务。

   新注册用户，需要等到第三个交易日才能使用第二套环境。

   账户、钱、仓跟第一套环境上一个交易日保持一致。

   交易阶段(服务时间)：交易日，16：00～次日09：00；非交易日，16：00～次日15：00。

   用户通过SimNow的账户（上一个交易日之前注册的账户都有效）接入环境，建议通过商业终端进行模拟交易的用户使用第一套环境。
   
** [[http://www.simnow.com.cn/static/softwareDownload.action][综合交易平台API]] 
   
   The website of /SimNow/ provides the download link of *CTP* API.

*** 支持版本 ( <= 6.3.15 穿透式)
    由于监管层要求，所有柜台系统需要满足穿透式监管要求，CTP也不例外。
    SimNow所有模拟环境都已经切换至穿透式，用户需要使用 CTP API 6.3.15以上版本，否则不能正常连接。

