include ../make/make.inc

#CC		=	
#LD     =	

BUILDDIR		=	.
BUILD_FLAGS		+= -Wno-deprecated-declarations
LIBPATHS		+= -L$(BASEDIR)/ThirdParty/libev/lib
LIBS        	:= -lev $(LIBS)
INCLUDEPATHS 	+= -I$(BASEDIR)/common -I$(BASEDIR)/io -I$(BASEDIR)/server_utils -I$(BASEDIR)/ThirdParty/libev/include
VPATH 			+= $(BASEDIR)/common $(BASEDIR)/io $(BASEDIR)/server_utils
RELEASE			:= ../../release/SignalAgent/bin


build			= ${RELEASE}/SignalAgent

build: ${build}
	@echo make target: $@
	

${RELEASE}/SignalAgent: CSocket.o CService.o CListener.o CBuffer.o CIOBase.o utils.o CTimer.o CRawIOReader.o CRawIOWriter.o \
  MurmurHash2.o CGlobalLock.o CGlobalSafeRawIOWriter.o CSignal.o CSignalAgent.o CSignalRequester.o CSignalServer.o main.o
	${CC} ${BUILD_FLAGS} $^ ${LIBPATHS} ${LIBS} ${INCLUDEPATHS} -o $@



# must put at the end
include ../make/tail.inc

